/* ============================================================
   JamDeck — STRINGS (i18n)  default = tr
   ============================================================ */

const STRINGS = {
  tr:{
    // brand / nav
    brand_sub:"OYUN JAMI",
    nav_section:"YÖNETİM",
    nav_download:"İndir & Doğrula",
    nav_organize:"Derle & Düzenle",
    nav_launch:"Başlat & Oyna",
    nav_setup:"Kurulum",
    settings:"Ayarlar",
    collapse:"Daralt",
    version:"Sürüm",

    // Setup
    setup_title:"Kurulum & Özelleştirme",
    setup_sub:"Jam'inizi markanıza göre yeniden tasarlayın — kod yok, sadece tıklayın.",
    sec_identity:"Jam Kimliği",
    sec_theme:"Tema",
    sec_effect:"Arka Plan Efekti",
    sec_language:"Dil",
    sec_behavior:"Başlatıcı Davranışı",
    sec_folders:"Klasörler",
    jam_name:"Jam Adı",
    jam_tagline:"Alt Başlık",
    logo_upload:"Logo",
    logo_hint:"Sürükleyip bırakın veya seçin · PNG/SVG",
    bg_upload:"Arka Plan Görseli / Videosu",
    bg_hint:"İsteğe bağlı · temalı arka plan da kullanabilirsiniz",
    use_plain_bg:"Bunun yerine düz temalı arka plan kullan",
    choose_file:"Dosya Seç",
    theme_presets:"Hazır Temalar",
    customize:"Özelleştir",
    col_accent:"Vurgu",
    col_accent2:"İkincil Vurgu",
    col_bg:"Arka Plan",
    col_surface:"Yüzey",
    col_text:"Metin",
    radius:"Köşe Yuvarlaklığı",
    glow:"Parlama Yoğunluğu",
    sharp:"Keskin",
    rounded:"Yuvarlak",
    effect_intensity:"Yoğunluk",
    effect_enabled:"Efekt Açık",
    language:"Dil",
    default_minutes:"Varsayılan Süre (dakika)",
    on_timeup:"Süre Bitince",
    timeup_kill:"Oyunu zorla kapat",
    timeup_warn:"Sadece uyar",
    timeup_return:"Listeye dön",
    kill_delay:"Kapatma Gecikmesi (sn)",
    kiosk_lock:"Kiosk Kilidi",
    kiosk_lock_sub:"Alt+F4 ve kapatmayı engeller",
    show_timer:"Zamanlayıcı Katmanını Göster",
    games_dir:"Oyun Klasörü",
    change:"Değiştir…",
    open_folder:"Klasörü Aç",
    save:"Kaydet",
    reset_defaults:"Varsayılana Sıfırla",
    export_config:"Dışa Aktar",
    import_config:"İçe Aktar",
    live_preview:"Canlı Önizleme",
    saved_ok:"Yapılandırma kaydedildi",
    reset_ok:"Varsayılanlara sıfırlandı",
    exported_ok:"Yapılandırma dışa aktarıldı",

    // Download
    dl_title:"İndir & Doğrula",
    dl_sub:"Tüm jam girişlerini itch.io'dan çekin ve arşiv bütünlüğünü kontrol edin.",
    target_folder:"Hedef klasör",
    jam_url:"Jam URL'si",
    api_key:"itch.io API Anahtarı",
    start_download:"İndirmeyi Başlat",
    integrity_check:"Bütünlük Kontrolü",
    cancel:"İptal",
    retry:"Tekrar Dene",
    working:"Çalışıyor…",
    now_downloading:"İndiriliyor",
    speed:"Hız",
    games_count:"oyun",
    dl_done:"Tüm indirmeler tamamlandı",
    verify_done:"Doğrulama tamamlandı",

    // Organize
    org_title:"Derle & Düzenle",
    org_sub:"Tüm arşivleri açın, iç içe klasörleri düzleştirin ve çöp dosyaları temizleyin.",
    auto_organize:"Otomatik Düzenle",
    org_done:"Düzenleme tamamlandı",
    sum_extracted:"arşiv açıldı",
    sum_fixed:"klasör düzeltildi",
    sum_removed:"çöp kaldırıldı",

    // Launcher
    games:"OYUNLAR",
    search_games:"Oyun ara…",
    refresh:"Listeyi Yenile",
    time_limit:"Süre (dk)",
    play:"BAŞLAT",
    switch_exe:"EXE Değiştir",
    exit_kiosk:"Kiosk'tan Çık",
    no_games_title:"Henüz oyun yok",
    no_games_sub:"İndir & Düzenle adımlarını çalıştırın",
    engine:"Motor",
    team:"Takım",

    // Timer
    times_up:"SÜRE BİTTİ",
    closing_in:"kapatılıyor",
    time_remaining:"Kalan Süre",

    // Modals
    exit_kiosk_q:"Kiosk modundan çıkılsın mı?",
    exit_kiosk_sub:"Bu, tam ekran başlatıcıyı kapatacak.",
    reset_q:"Varsayılanlara sıfırlansın mı?",
    reset_sub:"Tüm tema ve yapılandırma değişiklikleri kaybolacak.",
    confirm:"Onayla",
    yes_exit:"Evet, çık"
  },

  en:{
    brand_sub:"GAME JAM",
    nav_section:"MANAGE",
    nav_download:"Download & Verify",
    nav_organize:"Organize & Clean",
    nav_launch:"Play",
    nav_setup:"Setup",
    settings:"Settings",
    collapse:"Collapse",
    version:"Version",

    setup_title:"Setup & Customize",
    setup_sub:"Re-skin the launcher for your jam — no code, just click.",
    sec_identity:"Jam Identity",
    sec_theme:"Theme",
    sec_effect:"Background Effect",
    sec_language:"Language",
    sec_behavior:"Launcher Behavior",
    sec_folders:"Folders",
    jam_name:"Jam Name",
    jam_tagline:"Tagline",
    logo_upload:"Logo",
    logo_hint:"Drag & drop or choose · PNG/SVG",
    bg_upload:"Background Image / Video",
    bg_hint:"Optional · you can use a themed background instead",
    use_plain_bg:"Use a plain themed background instead",
    choose_file:"Choose File",
    theme_presets:"Theme Presets",
    customize:"Customize",
    col_accent:"Accent",
    col_accent2:"Accent 2",
    col_bg:"Background",
    col_surface:"Surface",
    col_text:"Text",
    radius:"Corner Radius",
    glow:"Glow Intensity",
    sharp:"Sharp",
    rounded:"Rounded",
    effect_intensity:"Intensity",
    effect_enabled:"Effect Enabled",
    language:"Language",
    default_minutes:"Default Time Limit (minutes)",
    on_timeup:"When Time's Up",
    timeup_kill:"Force-close game",
    timeup_warn:"Just warn",
    timeup_return:"Return to list",
    kill_delay:"Kill Delay (sec)",
    kiosk_lock:"Kiosk Lock",
    kiosk_lock_sub:"Disables Alt+F4 / close",
    show_timer:"Show Timer Overlay",
    games_dir:"Games Directory",
    change:"Change…",
    open_folder:"Open Folder",
    save:"Save",
    reset_defaults:"Reset to Defaults",
    export_config:"Export",
    import_config:"Import",
    live_preview:"Live Preview",
    saved_ok:"Configuration saved",
    reset_ok:"Reset to defaults",
    exported_ok:"Configuration exported",

    dl_title:"Download & Verify",
    dl_sub:"Pull all jam entries from itch.io and check archive integrity.",
    target_folder:"Target folder",
    jam_url:"Jam URL",
    api_key:"itch.io API Key",
    start_download:"Start Download",
    integrity_check:"Integrity Check",
    cancel:"Cancel",
    retry:"Retry",
    working:"Working…",
    now_downloading:"Downloading",
    speed:"Speed",
    games_count:"games",
    dl_done:"All downloads complete",
    verify_done:"Verification complete",

    org_title:"Organize & Clean",
    org_sub:"Unpack all archives, flatten nested folders, and remove junk.",
    auto_organize:"Auto-Organize",
    org_done:"Organization complete",
    sum_extracted:"archives extracted",
    sum_fixed:"folders fixed",
    sum_removed:"junk removed",

    games:"GAMES",
    search_games:"Search games…",
    refresh:"Refresh list",
    time_limit:"Time (min)",
    play:"PLAY",
    switch_exe:"Switch EXE",
    exit_kiosk:"Exit Kiosk",
    no_games_title:"No games yet",
    no_games_sub:"Run Download & Organize first",
    engine:"Engine",
    team:"Team",

    times_up:"TIME'S UP",
    closing_in:"closing in",
    time_remaining:"Time Remaining",

    exit_kiosk_q:"Exit kiosk mode?",
    exit_kiosk_sub:"This will close the fullscreen launcher.",
    reset_q:"Reset to defaults?",
    reset_sub:"All theme and configuration changes will be lost.",
    confirm:"Confirm",
    yes_exit:"Yes, exit"
  }
};

let LANG = "tr";
function t(key){ return (STRINGS[LANG] && STRINGS[LANG][key]) || (STRINGS.en[key]) || key; }
function setLanguage(lang){
  LANG = (lang==="en")?"en":"tr";
  document.documentElement.setAttribute("lang", LANG);
  if(window.__rerenderText) window.__rerenderText();
}
